// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/song.proto

package song

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Song struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Artist        string                 `protobuf:"bytes,3,opt,name=artist,proto3" json:"artist,omitempty"`
	Album         string                 `protobuf:"bytes,4,opt,name=album,proto3" json:"album,omitempty"`
	Genre         string                 `protobuf:"bytes,5,opt,name=genre,proto3" json:"genre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Song) Reset() {
	*x = Song{}
	mi := &file_proto_song_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Song) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Song) ProtoMessage() {}

func (x *Song) ProtoReflect() protoreflect.Message {
	mi := &file_proto_song_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Song.ProtoReflect.Descriptor instead.
func (*Song) Descriptor() ([]byte, []int) {
	return file_proto_song_proto_rawDescGZIP(), []int{0}
}

func (x *Song) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Song) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Song) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *Song) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *Song) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

type SongRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SongRequest) Reset() {
	*x = SongRequest{}
	mi := &file_proto_song_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SongRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongRequest) ProtoMessage() {}

func (x *SongRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_song_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongRequest.ProtoReflect.Descriptor instead.
func (*SongRequest) Descriptor() ([]byte, []int) {
	return file_proto_song_proto_rawDescGZIP(), []int{1}
}

func (x *SongRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SongList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Songs         []*Song                `protobuf:"bytes,1,rep,name=songs,proto3" json:"songs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SongList) Reset() {
	*x = SongList{}
	mi := &file_proto_song_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SongList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongList) ProtoMessage() {}

func (x *SongList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_song_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongList.ProtoReflect.Descriptor instead.
func (*SongList) Descriptor() ([]byte, []int) {
	return file_proto_song_proto_rawDescGZIP(), []int{2}
}

func (x *SongList) GetSongs() []*Song {
	if x != nil {
		return x.Songs
	}
	return nil
}

type SongInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Artist        string                 `protobuf:"bytes,2,opt,name=artist,proto3" json:"artist,omitempty"`
	Album         string                 `protobuf:"bytes,3,opt,name=album,proto3" json:"album,omitempty"`
	Genre         string                 `protobuf:"bytes,4,opt,name=genre,proto3" json:"genre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SongInput) Reset() {
	*x = SongInput{}
	mi := &file_proto_song_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SongInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongInput) ProtoMessage() {}

func (x *SongInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_song_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongInput.ProtoReflect.Descriptor instead.
func (*SongInput) Descriptor() ([]byte, []int) {
	return file_proto_song_proto_rawDescGZIP(), []int{3}
}

func (x *SongInput) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SongInput) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *SongInput) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *SongInput) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_song_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_song_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_song_proto_rawDescGZIP(), []int{4}
}

var File_proto_song_proto protoreflect.FileDescriptor

const file_proto_song_proto_rawDesc = "" +
	"\n" +
	"\x10proto/song.proto\x12\x04song\"p\n" +
	"\x04Song\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x03 \x01(\tR\x06artist\x12\x14\n" +
	"\x05album\x18\x04 \x01(\tR\x05album\x12\x14\n" +
	"\x05genre\x18\x05 \x01(\tR\x05genre\"\x1d\n" +
	"\vSongRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\",\n" +
	"\bSongList\x12 \n" +
	"\x05songs\x18\x01 \x03(\v2\n" +
	".song.SongR\x05songs\"e\n" +
	"\tSongInput\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x02 \x01(\tR\x06artist\x12\x14\n" +
	"\x05album\x18\x03 \x01(\tR\x05album\x12\x14\n" +
	"\x05genre\x18\x04 \x01(\tR\x05genre\"\a\n" +
	"\x05Empty2\xe0\x01\n" +
	"\vSongService\x12)\n" +
	"\n" +
	"CreateSong\x12\x0f.song.SongInput\x1a\n" +
	".song.Song\x12(\n" +
	"\aGetSong\x12\x11.song.SongRequest\x1a\n" +
	".song.Song\x12(\n" +
	"\tListSongs\x12\v.song.Empty\x1a\x0e.song.SongList\x12$\n" +
	"\n" +
	"UpdateSong\x12\n" +
	".song.Song\x1a\n" +
	".song.Song\x12,\n" +
	"\n" +
	"DeleteSong\x12\x11.song.SongRequest\x1a\v.song.EmptyB\x1eZ\x1cgrpc-song-manager/proto;songb\x06proto3"

var (
	file_proto_song_proto_rawDescOnce sync.Once
	file_proto_song_proto_rawDescData []byte
)

func file_proto_song_proto_rawDescGZIP() []byte {
	file_proto_song_proto_rawDescOnce.Do(func() {
		file_proto_song_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_song_proto_rawDesc), len(file_proto_song_proto_rawDesc)))
	})
	return file_proto_song_proto_rawDescData
}

var file_proto_song_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_song_proto_goTypes = []any{
	(*Song)(nil),        // 0: song.Song
	(*SongRequest)(nil), // 1: song.SongRequest
	(*SongList)(nil),    // 2: song.SongList
	(*SongInput)(nil),   // 3: song.SongInput
	(*Empty)(nil),       // 4: song.Empty
}
var file_proto_song_proto_depIdxs = []int32{
	0, // 0: song.SongList.songs:type_name -> song.Song
	3, // 1: song.SongService.CreateSong:input_type -> song.SongInput
	1, // 2: song.SongService.GetSong:input_type -> song.SongRequest
	4, // 3: song.SongService.ListSongs:input_type -> song.Empty
	0, // 4: song.SongService.UpdateSong:input_type -> song.Song
	1, // 5: song.SongService.DeleteSong:input_type -> song.SongRequest
	0, // 6: song.SongService.CreateSong:output_type -> song.Song
	0, // 7: song.SongService.GetSong:output_type -> song.Song
	2, // 8: song.SongService.ListSongs:output_type -> song.SongList
	0, // 9: song.SongService.UpdateSong:output_type -> song.Song
	4, // 10: song.SongService.DeleteSong:output_type -> song.Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_song_proto_init() }
func file_proto_song_proto_init() {
	if File_proto_song_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_song_proto_rawDesc), len(file_proto_song_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_song_proto_goTypes,
		DependencyIndexes: file_proto_song_proto_depIdxs,
		MessageInfos:      file_proto_song_proto_msgTypes,
	}.Build()
	File_proto_song_proto = out.File
	file_proto_song_proto_goTypes = nil
	file_proto_song_proto_depIdxs = nil
}
